### ISSUE TITLE
can this method use for Llama-2 series model?

### ISSUE THREAD

**Issue by skykiseki** [SafeAILab/RAIN#2]
I think the method should work for any decoder-only models, right?

**Comment by hongyanz** [comment]
Yes, it is useful for Llama-2 series model. Please check our paper where you can find the experiments there: https://arxiv.org/pdf/2309.07124.pdf

**Comment by skykiseki** [comment]
> Yes, it is useful for Llama-2 series model. Please check our paper where you can find the experiments there: https://arxiv.org/pdf/2309.07124.pdf

Sorry, I raised the wrong question title. What I want to ask is the method can work for any decoder-only method? I think RAIN can also apply on TinyLlama, OPT and other decoder-only method cause the forward-backward step needs to pre-decode the next token when the model inferencing, right?

**Comment by hongyanz** [comment]
Should work for any model, as long as the model has a reasonably good understanding about whether its output is harmful or not.

**Comment by skykiseki** [comment]
> Should work for any model, as long as the model has a reasonably good understanding about whether its output is harmful or not.

Yes, and I think RAIN's performance directly depends on model's safety guarding ability. Nice idea, learn a lot from your work, thx
